---

- name: Install chronograf
  include: "install-{{ ansible_os_family|lower }}.yml"

- name: Ensure chronograf config dir exists
  file:
    path:  "{{ chronograf_work_dir }}"
    state: directory
    owner: "{{ chronograf_user }}"
    group: "{{ chronograf_group }}"

- name: Update chronograf config file
  template:
    src:   config.toml.j2
    dest:  "{{ chronograf_work_dir }}/config.toml"
    owner: "{{ chronograf_user }}"
    group: "{{ chronograf_group }}"
    mode:  0664
  notify: Restart chronograf

- name: Update chronograf startup script envrionment variables file
  template:
    src:   etc.default.chronograf.j2
    dest:  /etc/default/chronograf
    owner: root
    group: root
    mode:  0664
  notify: Restart chronograf

- name: Start chronograf
  service: name=chronograf enabled=yes state=started
